[package]
name = "src-reduce-plugin-system"
version = "0.1.0"
authors = ["happysmile <812024380@qq.com>"]
edition = "2021"
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
swc = "0.259.4"
swc_common = "0.30.5"
swc_ecma_parser = "0.132.6"
